### ISSUE TITLE
Conflicting file names on Windows (blob.js and Blob.js)

### ISSUE THREAD

**Issue by sam-19** [e-alfred/epubreader#4]
Hey,

First off, it's great to see someone pick up development for this app! I would like to hep with developing it further, but there's a file name conflict that prevents me from cloning the app to a Windows machine. In `js/lib` there are files called blob.js and Blob.js. Both can't simultaneously exist in the same directory on Windows. I'm not sure what these files do actually, renaming blob.js to blobextend.js didn't seem to break anything at least in my short testing. If you could resolve this naming conflict, I could help out with the project. At the moment the first thing to do (in my opinion) is to move the database configuration from the xml file to `db/Migrations` ASAP, as leaving the xml file in place on current stable can result in serious problems, including permanent data loss.

Best regards,
Sam

**Comment by e-alfred** [comment]
Hello,

thanks for your help! Blob support should be available on all modern and supported browsers (see here: https://caniuse.com/#search=blob), so this is just one piece of legacy code that should be removed. I will take a look into it if it impacts anything, otherwise it can be removed without much trouble anyway.

**Comment by e-alfred** [comment]
Fixed by https://github.com/e-alfred/epubreader/commit/ea0ada73ead0d050e4d4b5fb7eebc095fd707b35.
